### ISSUE TITLE
Usage in real-world

### ISSUE THREAD

**Issue by xzpk22** [alexfrom0815/Online-3D-BPP-PCT#21]
Hello ! Thank you very much for this wonderful work!
I'd like to reproduce the experiment with a real robot (C-6 of your paper). I'm having trouble adjusting the code in order to continuously feed the PCT pipeline new boxes.
The random boxes seem to be generated in `PackingDiscrete.gen_next_box`, but the function is called at the end of `PackingDiscrete.step`, in `PackingDiscrete.cur_observation()`.

The ideal workflow, as I understand it, would be : 
- Capture a new Box (sx,sy,sz)
- Call `PackingDiscrete.gen_next_box `with box dimensions
- Generate the observation vector and forward the network with it
- Call `env.step()` with the **selected_leaf_node**
- Get the box target location from the latest box added in **env.packed**

Do you think that would that work correctly ? Did you do something similar for your real-world packing video ?
If you still have some code of that experiment somewhere, I would be very glad to consult it :)

Thanks again for sharing your work and for your time!

**Comment by alexfrom0815** [comment]
Hello, thank you very much for your attention. I think your understanding is very accurate. When we pack in the real-world, we can modify it like this. We have some projects that deploy packing robots in the real world, which is based on this logic. of. I'd be more than happy to help, unfortunately the code for the robot project cannot be released due to some non-disclosure agreements. This change is correct and easy to implement, so you can try it out.
